// Angular/src/app/todo/components/todo-case/todo-case.component.ts
import { Component, Input } from '@angular/core';
import { Todo } from '../../models/todo';
import { TodoService } from '../../services/todo.service';

@Component({
  selector: 'app-todo-case',
  templateUrl: './todo-case.component.html',
  styleUrls: ['./todo-case.component.scss', './todo-checkbox.component.scss']
})
export class TodoCaseComponent {
  @Input() todo!: Todo;
  editToggle: boolean = true;
  editText!: string;

  constructor(public todoService: TodoService) {

  }

  openEdit() {
    this.editToggle = false;
    this.editText = this.todo.title;
  }

  editCase() {
    if (!this.editText) return;
    this.todoService.editTodo(this.editText, this.todo.id);
    this.editToggle = true;
  }

}

<li>
  <div class="todo__list-case">
    <input type="checkbox" [checked]="todo.completed" />
    <label *ngIf="editToggle" (click)="todoService.toggleCompleted(todo.id)"></label>
    <p><span *ngIf="editToggle">{{todo.title}}</span>
      <input type="text" [(ngModel)]="editText" class="todo__list-edit-input" (blur)="editCase()"
        (keydown.enter)="editCase()" *ngIf="!editToggle" />
    </p>
  </div>
  <div class="todo__list-buttons">
    <button class="todo__list-edit" (click)="openEdit()">&#9998;</button>
    <button class="todo__list-remove" (click)="todoService.removeTodo(todo.id)">X</button>
  </div>
</li>

// React/src/components/todo-case/TodoCase.tsx
import { useState } from 'react';
import { Todo } from '../../types';
import { useAppDispatch } from '../../store/hook';
import { toggleCompleted, removeTodo, editTodo } from '../../store/todoSlice';


const TodoCase: React.FC<Todo> = ({ id, title, completed }) => {
  const [value, setValue] = useState(title);
  const [toggle, setToggle] = useState(true);
  const dispatch = useAppDispatch();

  const editTitle = (): void => {
    dispatch(editTodo({ id, title: value, completed }));
    setToggle(true);
  }

  const enterKeyDown: React.KeyboardEventHandler<HTMLInputElement> = (event) => {
    if (event.key === 'Enter') editTitle();
  }

  return (
    <li>
      <div className="todo__list-case">
        <input type="checkbox" checked={completed} onChange={() => dispatch(toggleCompleted(id))} />
        {toggle && <label onClick={() => dispatch(toggleCompleted(id))}></label>}
        <p>{toggle ? title : <input type="text"
          value={value}
          className="todo__list-edit-input"
          onChange={(e) => setValue(e.target.value)}
          onBlur={editTitle}
          onKeyDown={enterKeyDown}
        />}</p>
      </div>
      <div className="todo__list-buttons">
        <button className="todo__list-edit" onClick={() => setToggle(false)}>&#9998;</button>
        <button className="todo__list-remove" onClick={() => dispatch(removeTodo(id))}>X</button>
      </div>
    </li>
  );
}

export default TodoCase;
