// Angular/src/app/todo/components/todo-list/todo-list.component.ts
import { Component } from '@angular/core';
import { TodoService } from '../../services/todo.service';

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.scss']
})
export class TodoListComponent {
  constructor(public todoService: TodoService) {
    const getList = localStorage.getItem('todo')
    if (getList) todoService.loadingTodo(JSON.parse(getList));
  }
}

<ul class="todo__list">
    <app-todo-case *ngFor="let todo of todoService.getList()" [todo]="todo"></app-todo-case>
</ul>
<button class="todo__clear-items" (click)="todoService.clearList()">
    Clear items</button>

// React/src/components/todo-list/TodoList.tsx
import { useEffect } from 'react'
import { useAppSelector, useAppDispatch } from '../../store/hook';
import { clearList, loadingTodo } from '../../store/todoSlice';
import TodoItem from '../todo-case/TodoCase';


const TodoList: React.FC = () => {
  const dispatch = useAppDispatch();
  const todos = useAppSelector(state => state.todos.list);

  useEffect(() => {
    const getList = localStorage.getItem('todo')
    if (getList) dispatch(loadingTodo(JSON.parse(getList)))
  }, []);

  const clearTodoList = (): void => {
    dispatch(clearList());
  }

  return <>
    <ul className="todo__list">
      {todos.map((todo) => (
        <TodoItem
          key={todo.id}
          {...todo}
        />
      ))}
    </ul>
    {todos.length > 0 && <button
      className="todo__clear-items"
      onClick={clearTodoList}>
      Clear items</button>}
  </>
};

export default TodoList;
